# Generated by Django 4.2.7 on 2025-10-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, help_text='Cores disponíveis (ex: Preto,Branco,Azul)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Tamanhos disponíveis (ex: P,M,G,GG)', max_length=100),
        ),
    ]
