# Generated by Django 4.2.7 on 2025-10-24 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_colors_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem principal (para compatibilidade)', upload_to='products/'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para acessibilidade', max_length=200)),
                ('is_main', models.BooleanField(default=False, help_text='Imagem principal do produto')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens do Produto',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
